apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-api
  namespace: sirius
spec:
  selector:
    matchLabels:
      app: dep-api
  template:
    metadata:
      labels:
        app: dep-api
    spec:
      containers:
        - name: appapi
          image: appapi:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: my-appapi-env
              
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-info
  namespace: sirius
spec:
  selector:
    matchLabels:
      app: dep-info
  template:
    metadata:
      labels:
        app: dep-info
    spec:
      containers:
        - name: appinfo
          image: appinfo:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: my-appinfo-env

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-login
  namespace: sirius
spec:
  selector:
    matchLabels:
      app: dep-login
  template:
    metadata:
      labels:
        app: dep-login
    spec:
      containers:
        - name: applogin
          image: applogin:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: my-applogin-env