apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-api
  namespace: sirius
spec:
  selector:
    matchLabels:
      app: dep-api
  replicas: 5
  template:
    metadata:
      labels:
        app: dep-api
    spec:
      containers:
        - name: appapi
          image: yapedro/appapi:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: my-appapi-env
              
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-info
  namespace: sirius
spec:
  selector:
    matchLabels:
      app: dep-info
  replicas: 1
  template:
    metadata:
      labels:
        app: dep-info
    spec:
      containers:
        - name: appinfo
          image: yapedro/appinfo:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: my-appinfo-env

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-login
  namespace: sirius
spec:
  selector:
    matchLabels:
      app: dep-login
  replicas: 2
  template:
    metadata:
      labels:
        app: dep-login
    spec:
      containers:
        - name: applogin
          image: yapedro/applogin:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: my-applogin-env